### ISSUE TITLE
[SOLVED] While retriving a JSON data from the DHT you get it in string format

### ISSUE THREAD

**Issue by zo-el** [Holochain/dpki#13]
When U retrieve a JSON data from the chain we the right data but it comes as a string format which looses its usefulness.

**How can we go about this issue?**

is their a way to retrieve it in JSON format ? or should I work around it?

**Comment by artbrock** [comment]
If the entry type is defined as JSON in the DNA file, it **should** return as JSON. 

If it's defined as string... then string.

If it is NOT behaving that way, then I think that's a bug.

**Comment by zo-el** [comment]
It is returning a string. 
But if you use **JSON.parse** it will convert to a object and you can use it as a JSON.
Done
