### ISSUE TITLE
Diffrence between NucleusType and RibosomeType

### ISSUE THREAD

**Issue by zo-el** [Holochain/dpki#9]
Hi,
i have not found much info about these two topics and whats the difference when we use them.?

Because in the HC-scaffolding tool the zome has a NecleusType mentioned and not at RibosomeType. 
**when i define a NecleusType, during hc gen chain i get an error for the file that it points to is not fond. 
But if I use a RibosomeType it finds the file and works fine.**

**Note:** in the Example app's (clutter and holochat) RibosomeType is used not NecleusType

**Comment by zippy** [comment]
This is just a naming issue.  We switched from Nucleus to Ribosome, and we should updated that in the hcscaffold.  For now just edit it by hand.

**Comment by zo-el** [comment]
Cool.
